/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConsultaRouteImport } from './routes/consulta'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAtletasRouteImport } from './routes/_authenticated/atletas'
import { Route as AuthenticatedAutorizacoesRouteImport } from './routes/_authenticated/autorizacoes'
import { Route as AuthenticatedCentralRouteImport } from './routes/_authenticated/central'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedEventosRouteImport } from './routes/_authenticated/eventos'
import { Route as AuthenticatedKitsRouteImport } from './routes/_authenticated/kits'
import { Route as AuthenticatedLocaisRouteImport } from './routes/_authenticated/locais'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as EventoSlugKitRouteImport } from './routes/evento.$slug.kit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultaRoute = ConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtletasRoute = AuthenticatedAtletasRouteImport.update({
  id: '/atletas',
  path: '/atletas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutorizacoesRoute =
  AuthenticatedAutorizacoesRouteImport.update({
    id: '/autorizacoes',
    path: '/autorizacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentralRoute = AuthenticatedCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosRoute = AuthenticatedEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKitsRoute = AuthenticatedKitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLocaisRoute = AuthenticatedLocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EventoSlugKitRoute = EventoSlugKitRouteImport.update({
  id: '/evento/$slug/kit',
  path: '/evento/$slug/kit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consulta': typeof ConsultaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atletas': typeof AuthenticatedAtletasRoute
  '/autorizacoes': typeof AuthenticatedAutorizacoesRoute
  '/central': typeof AuthenticatedCentralRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/kits': typeof AuthenticatedKitsRoute
  '/locais': typeof AuthenticatedLocaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/evento/$slug/kit': typeof EventoSlugKitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/consulta': typeof ConsultaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/atletas': typeof AuthenticatedAtletasRoute
  '/autorizacoes': typeof AuthenticatedAutorizacoesRoute
  '/central': typeof AuthenticatedCentralRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/eventos': typeof AuthenticatedEventosRoute
  '/kits': typeof AuthenticatedKitsRoute
  '/locais': typeof AuthenticatedLocaisRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/evento/$slug/kit': typeof EventoSlugKitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/consulta': typeof ConsultaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/atletas': typeof AuthenticatedAtletasRoute
  '/_authenticated/autorizacoes': typeof AuthenticatedAutorizacoesRoute
  '/_authenticated/central': typeof AuthenticatedCentralRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/eventos': typeof AuthenticatedEventosRoute
  '/_authenticated/kits': typeof AuthenticatedKitsRoute
  '/_authenticated/locais': typeof AuthenticatedLocaisRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/evento/$slug/kit': typeof EventoSlugKitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/consulta'
    | '/reset-password'
    | '/atletas'
    | '/autorizacoes'
    | '/central'
    | '/dashboard'
    | '/entregas'
    | '/estoque'
    | '/eventos'
    | '/kits'
    | '/locais'
    | '/relatorios'
    | '/usuarios'
    | '/evento/$slug/kit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/consulta'
    | '/reset-password'
    | '/atletas'
    | '/autorizacoes'
    | '/central'
    | '/dashboard'
    | '/entregas'
    | '/estoque'
    | '/eventos'
    | '/kits'
    | '/locais'
    | '/relatorios'
    | '/usuarios'
    | '/evento/$slug/kit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/consulta'
    | '/reset-password'
    | '/_authenticated/atletas'
    | '/_authenticated/autorizacoes'
    | '/_authenticated/central'
    | '/_authenticated/dashboard'
    | '/_authenticated/entregas'
    | '/_authenticated/estoque'
    | '/_authenticated/eventos'
    | '/_authenticated/kits'
    | '/_authenticated/locais'
    | '/_authenticated/relatorios'
    | '/_authenticated/usuarios'
    | '/evento/$slug/kit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConsultaRoute: typeof ConsultaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  EventoSlugKitRoute: typeof EventoSlugKitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulta': {
      id: '/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof ConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atletas': {
      id: '/_authenticated/atletas'
      path: '/atletas'
      fullPath: '/atletas'
      preLoaderRoute: typeof AuthenticatedAtletasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autorizacoes': {
      id: '/_authenticated/autorizacoes'
      path: '/autorizacoes'
      fullPath: '/autorizacoes'
      preLoaderRoute: typeof AuthenticatedAutorizacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/central': {
      id: '/_authenticated/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof AuthenticatedCentralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos': {
      id: '/_authenticated/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AuthenticatedEventosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kits': {
      id: '/_authenticated/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof AuthenticatedKitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/locais': {
      id: '/_authenticated/locais'
      path: '/locais'
      fullPath: '/locais'
      preLoaderRoute: typeof AuthenticatedLocaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/evento/$slug/kit': {
      id: '/evento/$slug/kit'
      path: '/evento/$slug/kit'
      fullPath: '/evento/$slug/kit'
      preLoaderRoute: typeof EventoSlugKitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtletasRoute: typeof AuthenticatedAtletasRoute
  AuthenticatedAutorizacoesRoute: typeof AuthenticatedAutorizacoesRoute
  AuthenticatedCentralRoute: typeof AuthenticatedCentralRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedEventosRoute: typeof AuthenticatedEventosRoute
  AuthenticatedKitsRoute: typeof AuthenticatedKitsRoute
  AuthenticatedLocaisRoute: typeof AuthenticatedLocaisRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtletasRoute: AuthenticatedAtletasRoute,
  AuthenticatedAutorizacoesRoute: AuthenticatedAutorizacoesRoute,
  AuthenticatedCentralRoute: AuthenticatedCentralRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedEventosRoute: AuthenticatedEventosRoute,
  AuthenticatedKitsRoute: AuthenticatedKitsRoute,
  AuthenticatedLocaisRoute: AuthenticatedLocaisRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConsultaRoute: ConsultaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  EventoSlugKitRoute: EventoSlugKitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
